title: <p align="center"> Praneeth Kumar</p>
logo: /assets/img/logo.JPG

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/praneeth-kumar-55b075128/">LinkedIn</a> |
  <a href="https://github.com/ManiacMind">GitHub</a>
  
  <br>   
  Experienced Software Engineer with a demonstrated history of working in Health care industry.
  Skilled in Java, Rest API microservices using Springboot framework and
  a Certified Developer in TigerGraph.
  Also having keen interest and zeal to learn on Concepts of Analytics using Python , ML , AI
  combined with Big Data Problems using Spark,Pyspark.
  <br>
  </p>



theme: jekyll-theme-minimal
